Netl.o: \
	../../include/EXTERN.h \
	../../include/perl.h \
	../../include/XSUB.h \
	../../include/netl/global.h \
	../../include/netl/resolve.h \
	../../include/netl/options.h \
	../../include/netl/ether.h \
	../../include/netl/ip.h \
	../../include/netl/filter.h \
	../../include/netl/action.h \
	../../include/netl/config.h \
	../../include/netl/catch.h 
