.\" @(#)man page for netl network logger/sniffer
.\" copyright 1997 graham the ollis
.ad b
.TH dcp 1 "3 june 1997" "CORE software" "CORE software"
.AT 3
.de sh
.br
.ne 5
.PP
\fB\\$1\fR
.PP
..
.SH NAME
dcp \- discrete comunication protocol
.SH SYNOPSIS
.B dcp
mesage [port]
.SH DESCRIPTION
.I dcp
is a way of passing messages to 
.BR netl (8)
and related programs.  in the case of 
.BR netl (8)
there is currently only one message you can send it.  "netl:readconfig" will
order 
.BR netl (8)
(if it's listening, see the man page for details on the 
.I listen
directive) to terminate it's current configeration and read the 
netl.conf file again.  this is handy if you make modifications to netl.conf
while 
.BR netl (8)
is running.
.SH OPTIONS
none
.SH SEE ALSO
.BR neta (1),
.BR xd (1),
.BR netl (8),
.BR hwpassive (8)
.SH BUGS
almost certainly.  please send bug reports/fixes to me 
Graham THE Ollis <ollisg@ns.arizona.edu>
.SH COPYING
Copyright 1996, 1997 Graham THE Ollis
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.SH AUTHOR
Graham THE Ollis <ollisg@ns.arizona.edu>
