neta.o: \
	include/netl/global.h \
	include/netl/ether.h \
	include/netl/ip.h \
	include/netl/dump.h \
	include/netl/lookup.h \
	include/netl/options.h \
	include/netl/resolve.h 
check.o: \
	include/netl/global.h \
	include/netl/ether.h \
	include/netl/ip.h \
	include/netl/action.h \
	include/netl/filter.h \
	include/netl/config.h 
compiler.o: \
	include/netl/global.h \
	include/netl/action.h \
	include/netl/filter.h \
	include/netl/ether.h \
	include/netl/ip.h \
	include/netl/config.h \
	include/netl/filter.h \
	include/netl/resolve.h 
resolve.o: \
	include/netl/global.h \
	include/netl/resolve.h \
	include/netl/options.h \
	include/netl/io.h 
lookup.o: \
	include/netl/global.h \
	include/netl/ether.h \
	include/netl/lookup.h 
sighandle.o: \
	include/netl/global.h \
	include/netl/sighandle.h \
	include/netl/io.h 
netl.o: \
	include/netl/global.h \
	include/netl/ether.h \
	include/netl/ip.h \
	include/netl/netl.h \
	include/netl/sighandle.h \
	include/netl/io.h \
	include/netl/options.h \
	include/netl/filter.h \
	include/netl/action.h \
	include/netl/config.h \
	include/netl/resolve.h \
	include/netl/grab.h \
	include/netl/check.h \
	include/netl/compiler.h 
options.o: \
	include/netl/global.h \
	include/netl/ether.h \
	include/netl/ip.h \
	include/netl/netl.h \
	include/netl/global.h \
	include/netl/filter.h \
	include/netl/action.h \
	include/netl/config.h \
	include/netl/options.h \
	include/netl/io.h 
dump.o: \
	include/netl/dump.h 
xd.o: \
	include/netl/dump.h 
io.o: \
	include/netl/global.h \
	include/netl/io.h \
	include/netl/options.h 
filter.o: \
	include/netl/global.h \
	include/netl/io.h \
	include/netl/filter.h \
	include/netl/action.h \
	include/netl/ether.h \
	include/netl/ip.h \
	include/netl/config.h \
	include/netl/options.h 
action.o: \
	include/netl/global.h \
	include/netl/action.h \
	include/netl/filter.h \
	include/netl/ether.h \
	include/netl/ip.h \
	include/netl/config.h \
	include/netl/io.h 
ipv6.o: \
	include/netl/global.h \
	include/netl/ether.h \
	include/netl/ip.h 
main.o: \
	include/netl/global.h \
	include/netl/ether.h \
	include/netl/ip.h \
	include/netl/netl.h \
	include/netl/sighandle.h \
	include/netl/io.h \
	include/netl/options.h \
	include/netl/filter.h \
	include/netl/action.h \
	include/netl/config.h \
	include/netl/resolve.h \
	include/netl/grab.h \
	include/netl/check.h \
	include/netl/compiler.h 
catch.o: \
	include/netl/global.h \
	include/netl/catch.h \
	include/netl/io.h 
fred.o: 
