.\" @(#)man page for netl network logger/sniffer
.\" copyright 1997 graham the ollis
.ad b
.TH neta 1 "3 june 1997" "CORE software" "CORE software"
.AT 3
.de sh
.br
.ne 5
.PP
\fB\\$1\fR
.PP
..
.SH NAME
neta \- network packet analizer
.SH SYNOPSIS
.B neta
[
.B -v-
] [
.B -r-
] [
.B -h
] file [...]
.SH DESCRIPTION
.I neta
is a network packet analizer.  it was designed to decode an IP packet 
stored as a file.  usually this will be a packet dumped by 
.BR netl (8).
first the address is shown, followed by header data.  the final part is
a hex dump, which displays offset, hex data, and character data.
because the header data is interpreted for you, it is not included in
the hex dump.
.SH OPTIONS
all boolean options can be postpended with a \+ or \- in order turn them
on or off.  the default invokation is always +, but the default value may
vary.
.PP
.TP 8
.TP
.BR \-h
help.  print out usage information.
.PP
.TP
.BR \-r [+|-]
resolve IP numbers to their hostname (default is on).
.PP
.TP
.BR \-v [+|-]
display version number and copyright information (default is on).
.SH SEE ALSO
.BR dcp (1),
.BR xd (1),
.BR netl (8),
.BR hwpassive (8)
.SH BUGS
almost certainly.  please send bug reports/fixes to me 
Graham THE Ollis <ollisg@ns.arizona.edu>
.SH COPYING
Copyright 1996, 1997 Graham THE Ollis
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.SH AUTHOR
Graham THE Ollis <ollisg@ns.arizona.edu>
