/*
 * This file was generated automatically by xsubpp version 1.9507 from the 
 * contents of Netl.xs. Do not edit this file, edit Netl.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Netl.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include <netl/api.h>

static int
not_here(char *s)
{
    croak("%s not implemented on this architecture", s);
    return -1;
}

static double
constant(char *name, int arg)
{
    errno = 0;
    switch (*name) {
    case 'A':
	break;
    case 'B':
	break;
    case 'C':
	break;
    case 'D':
	break;
    case 'E':
	break;
    case 'F':
	break;
    case 'G':
	break;
    case 'H':
	break;
    case 'I':
	break;
    case 'J':
	break;
    case 'K':
	break;
    case 'L':
	break;
    case 'M':
	if (strEQ(name, "MAXICMP6TYPE"))
#ifdef MAXICMP6TYPE
	    return MAXICMP6TYPE;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MAXICMPCODE"))
#ifdef MAXICMPCODE
	    return MAXICMPCODE;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MAXICMPTYPE"))
#ifdef MAXICMPTYPE
	    return MAXICMPTYPE;
#else
	    goto not_there;
#endif
	break;
    case 'N':
	if (strEQ(name, "NETL_API_H"))
#ifdef NETL_API_H
	    return NETL_API_H;
#else
	    goto not_there;
#endif
	break;
    case 'O':
	break;
    case 'P':
	break;
    case 'Q':
	break;
    case 'R':
	break;
    case 'S':
	break;
    case 'T':
	break;
    case 'U':
	break;
    case 'V':
	break;
    case 'W':
	break;
    case 'X':
	break;
    case 'Y':
	break;
    case 'Z':
	break;
    }
    errno = EINVAL;
    return 0;

not_there:
    errno = ENOENT;
    return 0;
}


#line 115 "Netl.c"
XS(XS_Netl_constant)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Netl::constant(name,arg)");
    {
	char *	name = (char *)SvPV(ST(0),PL_na);
	int	arg = (int)SvIV(ST(1));
	double	RETVAL;

	RETVAL = constant(name, arg);
	ST(0) = sv_newmortal();
	sv_setnv(ST(0), (double)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Netl_netl)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Netl::netl(dev)");
    {
	char *	dev = (char *)SvPV(ST(0),PL_na);
	int	RETVAL;
#line 119 "Netl.xs"
		RETVAL = netl(dev);
#line 143 "Netl.c"
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Netl__Guts__get_yy_line_number)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: Netl::Guts::_get_yy_line_number()");
    {
	int	RETVAL;
#line 130 "Netl.xs"
		RETVAL = netl_guts_yy_line_number;
#line 159 "Netl.c"
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Netl__Guts__set_yy_line_number)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Netl::Guts::_set_yy_line_number(value)");
    {
	int	value = (int)SvIV(ST(0));
#line 139 "Netl.xs"
		netl_guts_yy_line_number = value;
#line 175 "Netl.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Netl__Config_readfile)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Netl::Config::readfile(filename)");
    {
	char *	filename = (char *)SvPV(ST(0),PL_na);
#line 148 "Netl.xs"
		netl_config_readfile(filename, 1);
#line 189 "Netl.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Netl__Config_parseline)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Netl::Config::parseline(line)");
    {
	char *	line = (char *)SvPV(ST(0),PL_na);
#line 155 "Netl.xs"
		netl_config_parseline(line);
#line 203 "Netl.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Netl__Config_pre)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: Netl::Config::pre()");
    {
#line 161 "Netl.xs"
		netl_config_pre();
#line 216 "Netl.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Netl__Config_post)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: Netl::Config::post()");
    {
#line 167 "Netl.xs"
		netl_config_post();
#line 229 "Netl.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Netl__Config_clear)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: Netl::Config::clear()");
    {
#line 173 "Netl.xs"
		netl_config_clear();
#line 242 "Netl.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Netl__Catch_prepare)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Netl::Catch::prepare(fd)");
    {
	int	fd = (int)SvIV(ST(0));
#line 181 "Netl.xs"
		netl_catch_prepare(fd);
#line 256 "Netl.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Netl__Catch_fork)
{
    dXSARGS;
    if (items < 1)
	croak("Usage: Netl::Catch::fork(prog, ...)");
    {
	char *	prog = (char *)SvPV(ST(0),PL_na);
#line 188 "Netl.xs"
	STRLEN n_a;
#line 270 "Netl.c"
	int	RETVAL;
#line 190 "Netl.xs"
		int i;
		char *argv[items+1];
		argv[0] = prog;
		for(i=1; i<items; i++) {
			argv[i] = (char *) SvPV(ST(i), n_a);
		}
		argv[i] = NULL;
		RETVAL = netl_catch_fork(prog, argv);
#line 281 "Netl.c"
	ST(0) = sv_newmortal();
	sv_setiv(ST(0), (IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Netl__Catch_catch)
{
    dXSARGS;
    if (items != 0)
	croak("Usage: Netl::Catch::catch()");
    SP -= items;
    {
#line 204 "Netl.xs"
		netl_catch_t *re;
#line 297 "Netl.c"
#line 206 "Netl.xs"
		re = netl_catch_catch();
		if(re == NULL) {
			/* nothing */
		} else if(re->packet_len == -1) {
			EXTEND(SP, 2);
			PUSHs(sv_2mortal(newSVpvn("-1", 2)));
			PUSHs(sv_2mortal(newSVpvn("died", 4)));
		} else if(re->packet_len == -2) {
			EXTEND(SP, 2);
			PUSHs(sv_2mortal(newSVpvn("-2", 2)));
			PUSHs(sv_2mortal(newSVpvn(re->name, strlen(re->name))));
		} else {
			EXTEND(SP, 2);
			PUSHs(sv_2mortal(newSVpv(re->name, strlen(re->name))));
			PUSHs(sv_2mortal(newSVpvn(re->packet, re->packet_len)));
		}
#line 315 "Netl.c"
	PUTBACK;
	return;
    }
}

XS(XS_Netl__Packet_check)
{
    dXSARGS;
    if (items != 2)
	croak("Usage: Netl::Packet::check(dg, size)");
    {
	char *	dg = (char *)SvPV(ST(0),PL_na);
	size_t	size = (size_t)SvIV(ST(1));
#line 230 "Netl.xs"
		netl_packet_check(dg, size);
#line 331 "Netl.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Netl__Generate_c)
{
    dXSARGS;
    if (items != 1)
	croak("Usage: Netl::Generate::c(fp)");
    {
	FILE *	fp = IoIFP(sv_2io(ST(0)));
#line 238 "Netl.xs"
		netl_generate_c(fp);	/* i really have no idea if this works */
#line 345 "Netl.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Netl)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Netl::constant", XS_Netl_constant, file);
        newXS("Netl::netl", XS_Netl_netl, file);
        newXS("Netl::Guts::_get_yy_line_number", XS_Netl__Guts__get_yy_line_number, file);
        newXS("Netl::Guts::_set_yy_line_number", XS_Netl__Guts__set_yy_line_number, file);
        newXS("Netl::Config::readfile", XS_Netl__Config_readfile, file);
        newXS("Netl::Config::parseline", XS_Netl__Config_parseline, file);
        newXS("Netl::Config::pre", XS_Netl__Config_pre, file);
        newXS("Netl::Config::post", XS_Netl__Config_post, file);
        newXS("Netl::Config::clear", XS_Netl__Config_clear, file);
        newXS("Netl::Catch::prepare", XS_Netl__Catch_prepare, file);
        newXS("Netl::Catch::fork", XS_Netl__Catch_fork, file);
        newXS("Netl::Catch::catch", XS_Netl__Catch_catch, file);
        newXS("Netl::Packet::check", XS_Netl__Packet_check, file);
        newXS("Netl::Generate::c", XS_Netl__Generate_c, file);
    XSRETURN_YES;
}

