gnr.o: \
	../include/netl/global.h \
	../include/netl/filter.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/action.h \
	../include/netl/config.h \
	../include/netl/io.h \
	../include/netl/resolve.h 
udp4.o: \
	../include/netl/global.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/action.h \
	../include/netl/filter.h \
	../include/netl/config.h \
	filt.h 
ip4.o: \
	../include/netl/global.h \
	../include/netl/filter.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/action.h \
	../include/netl/config.h \
	filt.h 
icmp4.o: \
	../include/netl/global.h \
	../include/netl/filter.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/action.h \
	../include/netl/config.h \
	filt.h 
stub.o: \
	../include/netl/global.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/filter.h \
	../include/netl/action.h \
	../include/netl/config.h 
ip.o: \
	../include/netl/global.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/filter.h \
	../include/netl/action.h \
	../include/netl/config.h 
tcp.o: \
	../include/netl/global.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/filter.h \
	../include/netl/action.h \
	../include/netl/config.h 
ip6.o: \
	../include/netl/global.h \
	../include/netl/filter.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/action.h \
	../include/netl/config.h \
	filt.h 
tcp4.o: \
	../include/netl/global.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/action.h \
	../include/netl/filter.h \
	../include/netl/config.h \
	filt.h 
ping.o: \
	../include/netl/global.h \
	../include/netl/filter.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/action.h \
	../include/netl/config.h \
	../include/netl/io.h \
	../include/netl/resolve.h 
icmp.o: \
	../include/netl/global.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/filter.h \
	../include/netl/action.h \
	../include/netl/config.h 
tcp6.o: \
	../include/netl/global.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/action.h \
	../include/netl/filter.h \
	../include/netl/config.h \
	filt.h 
icmp6.o: \
	../include/netl/global.h \
	../include/netl/filter.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/action.h \
	../include/netl/config.h \
	filt.h 
udp.o: \
	../include/netl/global.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/filter.h \
	../include/netl/action.h \
	../include/netl/config.h 
udp6.o: \
	../include/netl/global.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/action.h \
	../include/netl/filter.h \
	../include/netl/config.h \
	filt.h 
raw.o: \
	../include/netl/global.h \
	../include/netl/filter.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/action.h \
	../include/netl/config.h \
	filt.h 
ignp.o: \
	../include/netl/global.h \
	../include/netl/filter.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/action.h \
	../include/netl/config.h \
	filt.h 
dcp.o: \
	../include/netl/global.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/io.h \
	../include/netl/action.h \
	../include/netl/filter.h \
	../include/netl/config.h \
	../include/netl/options.h \
	../include/netl/resolve.h 
tcp4_next.o: \
	../include/netl/global.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/action.h \
	../include/netl/filter.h \
	../include/netl/config.h \
	filt.h 
hwpassive.o: \
	../include/netl/global.h \
	../include/netl/ether.h \
	../include/netl/ip.h \
	../include/netl/filter.h \
	../include/netl/action.h \
	../include/netl/config.h \
	../include/netl/io.h \
	../include/netl/resolve.h 
